### ISSUE TITLE
Updates on tumblr.d.ts?

### ISSUE THREAD

**Issue by ivycheung** [tumblr/tumblr.js#101]
I noticed that tumblr.d.ts hasn't been updated since the repo started and it has been outdated compared to its javascript counterpart. Are there any thoughts to have them updated so they match? I ended up deleting the file in order to get my application to detect the new methods.

Thanks!

**Comment by sirreal** [comment]
We'll be doing some work on this library and one thing I'd like to see is better and more up to date types.
