### ISSUE TITLE
Threads, combined photo/text posts and replies

### ISSUE THREAD

**Issue by gsteri1** [tumblr/tumblr.js#104]
Hi! I am successfully able to submit text posts or photo posts independently into tumblr via the legacy endpoints in the tumblr.js libbrary. The issue is that I would like to submit a mixed text/photo img post. The images are computer generated, so I insert them as a data64 string. 

Here are the things that I have tried:
1.I have tried to use the generic createPost method and supply the "text" parameters as well as the image parameters. The only thing posted is the text. 

2. I have attempted to createPost, then I call editPost using the id_string in the successful initial post. In the editPost, I submit the image parameters (which do seem to work in the createPhotoPost call). The edit post returns successfully with the original id_string, but I do not see an image posted. 

I am sure this is something dumb I am doing. Additionally, in playing with the api I don't see how one would build a thread. Is that the "chat" message? If so, how does one go about responding to it? In analyzing the message flow of the web site I see the following sent by the browser to tumblr: {"post_id":"643848899420930048","reply_text":"Blah blah bla....","reblog_key":"Tk00VfYk","tumblelog":"commodityvol"} I cannot see an analogue in the api. Again, probably my ignorance here. 

Thank you.

**Comment by sirreal** [comment]
I understand there are two issues here.

**First:** Legacy post creation doesn't support mixed-format posts well. This should be resolved by introducing NPF post creation (#165). The library doesn't support that yet, but it's on the roadmap for the next release.

**Second:** You want to build threads. I'm not sure what this means, but I believe you want to create a reblog trail. That's currently available via the `reblogPost` method, although that is a legacy post method and should be considered deprecated in favor of the upcoming NPF post creation method which will support reblogs.

I'll close this issue, I think it should all be covered by adding an NPF post creation method (#165). Please comment again if that's incorrect.
