### ISSUE TITLE
Does tumblr.js support NPF post creation ?

### ISSUE THREAD

**Issue by clvgt12** [tumblr/tumblr.js#105]
Hello.   I am trying to create a simple NPF post using Tumblr.js 3.0.0.

Running this ->
```js
'use strict';
const tumblr=require('tumblr.js');
const util=require('util');

const client = tumblr.createClient({
// OAuth credentials ...
});

function callback(err,resp) {
   var errString=util.inspect(err,{depth:null});
   var respString=util.inspect(resp,{depth:null});
   console.log(`error string => <---<${errString}>--->`);
   console.log(`error string => <---<${respString}>--->`);
}
client.postRequest('/v2/blog/mytestblog.tumblr.com/post',
               {"state":"draft","type":"text","title":"Legacy Text Post","body":"this was the result of a API call using tumblr.js"},
               callback);
client.postRequest('/v2/blog/mytestblog.tumblr.com/posts',
               {"state":"draft","content":[{"type":"text","text":"NPF Post"},{"type":"text","text":"this was the result of a API call using tumblr.js"}]},
               callback);
```

yields this ->

```XXXX@martini:~/src/tumblr-api-hacking$ ./tumblr-api-hacking.js
error string => <---<Error: form-data: **Arrays are not supported.**
   at FormData.append (/home/XXXX/node_modules/form-data/lib/form_data.js:66:17)
    at postRequest (/home/XXXX/node_modules/tumblr.js/lib/tumblr.js:554:14)
    at TumblrClient.postRequest (/home/XXXX/node_modules/tumblr.js/lib/tumblr.js:935:12)
    at Object.<anonymous> (/home/XXXX/src/tumblr-api-hacking/tumblr-api-hacking.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)>--->
error string => <---<null>--->
error string => <---<null>--->
error string => <---<{ id: 656235127042687000,
  id_string: '656235127042686977',
  state: 'draft',
  display_text: 'Saved to your drafts.' }>--->
```
The legacy post is created successfully, while the API call to create the NPF post throws the error.

It appears the use of the 'FormData.append' method is preventing the sending of the NPF content block in the API call.   Since the NPF content block is a Javascript array, would this client library need modified to create a successful NPF post ?

**Comment by shahkashani** [comment]
I don't think it supports posting to NPF out of the box. This is not the most succinct example, but I had to mess around quite a bit to get it to work, at least for more complex use-cases like image posts: https://github.com/shahkashani/stills/blob/master/lib/destinations/tumblr.js

**Comment by clvgt12** [comment]
> I don't think it supports NPF out of the box. This is not the most succinct example, but I had to mess around quite a bit to get it to work, at least for more complex use-cases like image posts: https://github.com/shahkashani/stills/blob/master/lib/destinations/tumblr.js

Thanks.   It looks like you are not using the official tumblr library to create the NPF post, rather you made your own.

**Comment by sirreal** [comment]
It does not support it right now, but it should.

**Comment by sirreal** [comment]
I consider this a requirement for the next release so NPF post creation should be coming soon (#165).
