### ISSUE TITLE
Feature Request: Add Alt Text to images

### ISSUE THREAD

**Issue by nolanfilter** [tumblr/tumblr.js#164]
Hello! I'm using tumblr.js to upload a daily image post and would like to add alt text to the image. Currently I put the image description in the caption, but I'd like to match standard accessibility practices.

I'm using the createPhotoPost() method to post, but it doesn't allow for alt text in the options. I've also tried using the postRequest() method to post to the NPF endpoint, but the library isn't prepared to turn content blocks in the params object into a form ([this is the issue I've run into](https://github.com/tumblr/tumblr.js/issues/105)).

Ideally the library would accept alt text as an option on post create methods. If that's not possible, is there a workaround you can suggest? Thank you!

**Comment by sirreal** [comment]
The library should support this. I'm planning to work on an NPF post creation method (#165). I suspect that will solve the issue as we should be able to add a content block like:

```jsonc
{
  type: "image",
  alt_text: "The alternate text for the image block.",
  //…
}
```

**Comment by sirreal** [comment]
Good news! This should be supported as of `tumblr.js@4.0.0-alpha.1` (currently tagged `next`).

You can see a working example of how to post with the library in the integration test suite:

https://github.com/tumblr/tumblr.js/blob/7845924a9048a2ed8d8cc8b4c7cc45db8b03d1f6/integration/write.mjs#L139-L172
