### ISSUE TITLE
Tumblr API is vital component of app

### ISSUE THREAD

**Issue by tianBreznik** [tumblr/tumblr.js#197]
Hi! I plan to use Tumblr.js in my little website project. However, I cannot register my application obviously, because it does not exist without Tumblr.js, which is going to play a vital part in it. What can I do? Is there a way to obtain the API Key without registering an actual hosted app?

**Comment by sanmai** [comment]
Could you try filling this form? It should be all you need.
https://www.tumblr.com/oauth/register

**Comment by tianBreznik** [comment]
thanks for the answer! It's exactly this form that I can't get past, as I have no application as of yet and hence also no callback URL. Is there some defaults or hard coded answers I could give?

**Comment by sanmai** [comment]
You can use a localhost URL for a callback.

**Comment by tianBreznik** [comment]
ah nice! Same for the application website? Or maybe I can provide my own personal website there? appreciate the help!

**Comment by sanmai** [comment]
You can provide any address you control. And you can change it later to something more fitting :slightly_smiling_face:
