### ISSUE TITLE
Access x-ratelimit* headers in tumblr.js 

### ISSUE THREAD

**Issue by j0rd** [tumblr/tumblr.js#20]
Is there a way to access the headers from the request tumblr.js makes. I need access to the x-ratelimit headers tumblr sends. I don't believe there's anything that exposes them, and also can't monkey patch easily since it's a privately scoped function.

    function requestCallback(callback) {   
      if (!callback) return;  
      return function (err, response, body) {  
        if (err) return callback(err);  
        var ratelimit_headers = {}; 
        for(var key in response.headers) {
          if(key.match(/x-ratelimit/)) { 
            ratelimit_headers[key] = response.headers[key];
          }  
        }
        /* HERES MY RATE LIMIT HEADERS */
        console.log("RATELIMIT HEADERS: ", ratelimit_headers);  
        if (response.statusCode >= 400) { 
          var err = body.meta ? body.meta.msg : body.error; 
          return callback(new Error('API error: ' + response.statusCode + ' ' + err)); 
        } 
        return callback(null, body.response);
      };
    }

**Comment by selfcontained** [comment]
What about just returning the `response` object for non-error responses as the 3rd argument [here](https://github.com/tumblr/tumblr.js/blob/master/lib/tumblr.js#L253):

```javascript
if (body && body.response) {
    return callback(null, body.response, response);
}
```

**Comment by j0rd** [comment]
That would work

**Comment by kmck** [comment]
closing this since third argument has been added in `v1.0.0`: https://github.com/tumblr/tumblr.js/blob/477600f2fd3128e61b0a6536297b9224329fcad6/lib/tumblr.js#L108-L129
