### ISSUE TITLE
Multiple image posting support

### ISSUE THREAD

**Issue by matthewisabel** [tumblr/tumblr.js#24]
Posting photosets isn't currently supported. Adding this issue in for reference if someone is ever looking for information on this in the issue history.

I've made a pull for it here: https://github.com/tumblr/tumblr.js/pull/23.

**Comment by jonbro** [comment]
anyone that has control over this repo paying attention? This would be really nice to have in the official api, since it is supported . . .

**Comment by Nedudi** [comment]
Your brunch just solve my life and saved tons of time!!!
Thanks a lot!! If you need beer, vodka, anything else, i can send it :)
Super great
@Tumblr, why this repo is su outdated ((((

**Comment by kmck** [comment]
we haven't forgotten about this. 😁 

there's some inconsistent behavior around photosets using `source` and `data64` on the api side that i want to iron out that makes me hesitant to have this implemented in the client right this second,

**Comment by Dooblr** [comment]
+1 

been awhile, any update on this?
