### ISSUE TITLE
Posting photo with empty caption causes 401 error

### ISSUE THREAD

**Issue by hyperboloid** [tumblr/tumblr.js#30]
Not sure exactly what the cause is, but passing empty parameters (e.g. caption) into the TumblrClient.photo function causes the Tumblr API to return a 401 Not Authorized error. I think it might have something to do with signing the request.

Since captions were user-generated on our platform, this caused a puzzling intermittent 401 error. Please fix this or at least update the documentation to warn people not to include empty parameters.

**Comment by KevinTCoughlin** [comment]
@hyperboloid: Can you provide sample code that 401s? I was able to create a photo post with and without a caption using the following code snippet (keys replaced with comments):

```js
'use strict';

var tumblr = require('tumblr.js');
var client = tumblr.createClient({
    consumer_key: // consumer key,
    consumer_secret: // consumer secret,
    token: // oauth token,
    token_secret: // oauth secret
});

var options = {
    source: 'http://cdni.wired.co.uk/620x413/s_v/shutterstock_65735200.jpg'
};

client.photo('kevintcoughlin', options, function(err, data) {
    console.log(err, data);
});
```

Are you supplying a blogname as the first parameter?

**Comment by hyperboloid** [comment]
If a parameter is empty, then it results in a 401 response:
```
'use strict';

var tumblr = require('tumblr.js');
var client = tumblr.createClient({
    consumer_key: '', // consumer key
    consumer_secret: '', // consumer secret
    token: '', // oauth token
    token_secret: '', // oauth secret
});

var photo_caption = "";
var options = {
    source: 'http://cdni.wired.co.uk/620x413/s_v/shutterstock_65735200.jpg',
    caption: photo_caption
};

client.photo('kevintcoughlin', options, function(err, data) {
    console.log(err, data); // [Error: API error: 401 Not Authorized] undefined
});
```
Result is a 401 response which can be confusing because it is not an authentication issue.

**Comment by kmck** [comment]
@hyperboloid: are you only having the issue with photo posts? it worked fine for me using an empty string for `caption` or omitting the key, so it might be missing/invalid credentials.
