### ISSUE TITLE
How to post to queue

### ISSUE THREAD

**Issue by leonardoflores** [tumblr/tumblr.js#31]
I'm using client.txt from the post methods. How can I post to queue instead of the published default?

**Comment by KevinTCoughlin** [comment]
You can set the state to `queue` in your posting options object to queue. For example:

```js
client.text(blogName, { state: queue }, callback);
```

Ref: https://www.tumblr.com/docs/en/api/v2#posting

**Comment by leonardoflores** [comment]
Thanks, Kevin.

On Thu, Jun 4, 2015 at 9:55 PM, Kevin Coughlin <notifications@github.com>
wrote:

> You can set the state to queue in your posting options object to queue.
> For example:
>
> client.text(blogName, { state: queue }, callback);
>
> Ref: https://www.tumblr.com/docs/en/api/v2#posting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tumblr/tumblr.js/issues/31#issuecomment-109123920>.
>



-- 

Leonardo Flores, Ph.D.
Associate Professor of English, UPR: Mayagüez
Treasurer, Electronic Literature Organization
Fulbright Program Adviser
Fulbright Campus Representative
Blog: leonardoflores.net
Featured project: I ♥ E-Poetry <http://iloveepoetry.com/>
