### ISSUE TITLE
API Usage clarification

### ISSUE THREAD

**Issue by achunt2143** [tumblr/tumblr.js#318]
Hi,
I want to get some clarification that my project is allowed per the API agreement. I have created a tumblr client for webOS, but wanted to get clarification on this section from the API Agreement:

> Don't re-implement the Dashboard, and don't recreate complete Tumblr functions or clients on a platform where Tumblr already has an official client (like web, iPhone, Android, or Windows Phone 8).

Would doing something like this, where the user logs in and shows their dashboard, be classified as 're-implementing the Dashboard'?

![Screenshot 2024-03-15 at 1 31 47 PM](https://github.com/tumblr/tumblr.js/assets/43080643/4ccb9648-fa63-4e03-99c3-18d09ad5b42b)

**Comment by sirreal** [comment]
Thanks for asking about usage, but this isn't a good place to handle that request. Will you please contact Tumblr Support?

https://www.tumblr.com/support
