### ISSUE TITLE
Get Access Token

### ISSUE THREAD

**Issue by gianlucatursi** [tumblr/tumblr.js#33]
I can get the access token of tumblr through the javascript library?

**Comment by ceykooo** [comment]
No, this library assumes you already have OAuth credentials. You can use a different library for completing the OAuth flow and obtaining credentials, e.g. [request](https://www.npmjs.com/package/request#oauth-signing).

**Comment by chovy** [comment]
You're examples should be updated to show how to do this.

**Comment by codeactual** [comment]
@chovy It would be helpful to know exactly what documentation gap you're expecting. The first line of the readme links to API key doc content that is also present in the readme itself.

**Comment by chovy** [comment]
```
var tumblr = require('tumblr.js');
var client = tumblr.createClient({
  consumer_key: '<consumer key>',
  consumer_secret: '<consumer secret>',
  token: '<oauth token>',
  token_secret: '<oauth token secret>'
});
```

This is step 3. Step 1 and 2 are not documented (how do get token and secret token).

**Comment by kmck** [comment]
@chovy i threw this together a while ago, but it might be helpful: https://github.com/kmck/tumblr-oauth
