### ISSUE TITLE
Errors in Nested Dependencies

### ISSUE THREAD

**Issue by chadfurman** [tumblr/tumblr.js#39]
Not sure if I should bother reporting this here, as it seems to be a hard-requirement in the nested dependencies.  However, I noticed that when I try to make posts in node 0.12.4 on Ubuntu 14.04 using tumblr.js I receive the following:

me@here:~/code/tumblr-lorem$ node tumblrLorem.js 
configuring application
including dependencies
preparing oauth
connected
submitting photo post: {
    "type": "photo",
    "tags": [
        "cross-platform",
        "online",
        "multi-byte",
        "primary"
    ],
    "caption": "iusto asperiores ullam consequuntur amet repudiandae natus voluptatem",
    "link": "https://brody.com",
    "source": "http://lorempixel.com/136/372"
}
/home/me/code/tumblr-lorem/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41
      stream.on('data', this._checkDataSize.bind(this));
             ^
TypeError: undefined is not a function
    at FormData.CombinedStream.append (/home/me/code/tumblr-lorem/node_modules/tumblr.js/node_modules/request/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:41:14)

this "combined_stream" thing is a nested dependency of form-data, and form-data is using a hard-coded version of 0.0.3 -- combined_stream is upto 1.0.5:  https://www.npmjs.com/package/combined-stream

This might be due to a hardcoded parent dependency?  Dunno.  But it's causing my posting to not go through.  I can manually update the package files myself, but that isn't very good.

My code is here:
https://github.com/shadesoflight/tumblr-lorem/blob/develop/tumblrLorem.js#L39

**Comment by kmck** [comment]
hey, sorry for the non-response from our end. can you update your sample to the latest `tumblr.js` and let me know if you're still having an issue? the dependencies in `package.json` were a little wonky, but it should be better now.
