### ISSUE TITLE
Tumblr.js Link posts API not the same as website

### ISSUE THREAD

**Issue by pleaseshutup** [tumblr/tumblr.js#41]
I'd like to be able to post link posts on a blog exactly the same way as if you were to go on the regular user interface and choose a "link" post and paste in a URL. It automatically grabs the image, sizes it, sets the title and a body/caption.

How do I go about doing this with the tumblr.js api wrapper?

**Comment by KevinTCoughlin** [comment]
This is a feature of the rich text editor used on the web. It fetches open graph data and autofills the post's meta. I don't believe this is something we want to support in the API as it is a client implementation.

**Comment by pleaseshutup** [comment]
There is no manual way to achieve it such as being able to update the post's meta?

**Comment by kmck** [comment]
This isn't possible via the API right now, unfortunately. Adding support isn't on the roadmap yet, but maybe someday.

**Comment by shahkashani** [comment]
Will re-open this issue when the API supports it!
