### ISSUE TITLE
Posting inline photos

### ISSUE THREAD

**Issue by guypursey** [tumblr/tumblr.js#44]
**On Tumblr's UI, it's possible to add inline photos to a post if you are in rich-text mode. It would be useful to be able to upload photos for inline use through the API.**

When you upload through the UI, the photo is uploaded to Tumblr and the URL is then added to the source code of the post. You can see this by switching from rich-text to HTML or Markdown modes.

The photo is uploaded to a location similar to photo-type posts' photos but the filename seems to be obfuscated and prepended with `tumblr_inline_`.

I can't see a way to do this through the API at the moment, except by adding them as draft photo posts which is far ideal, but there may be a way I'm not aware that could be added as a feature/function of this package.

**Comment by kmck** [comment]
you're correct that there's no api endpoint for uploading arbitrary images for inline use like that currently.

a workaround would be to upload the images somewhere else, include the images as external urls, and use the `native_inline_photos: true` to convert them to `tumblr_inline_` images

**Comment by kmck** [comment]
going to close this for now, since we're not adding the feature
