### ISSUE TITLE
[Error: API error: 401 Unauthorized] 

### ISSUE THREAD

**Issue by jlobos27** [tumblr/tumblr.js#46]
Hi,

I get authentication error in reblog of post, the code is based from https://api.tumblr.com/console/calls/post/reblog i failed to resolve :tired_face:

```js
var tumblr = require('tumblr.js');

var client = tumblr.createClient({
  consumer_key: '',
  consumer_secret: '',
  token: '',
  token_secret: ''
});

client.reblog('biorandom.tumblr.com', {
  id: 132680518497,
  reblog_key: '5UmjEEzJ'
}, function (err, data) {
  console.log(err, data);
});

```

out

```
[Error: API error: 401 Unauthorized] undefined
```

**Comment by KevinTCoughlin** [comment]
Hey @jlobos27, I assume you were using OAuth credentials for that blog and omitted them for this example. Is that correct? Just asking since incorrect credentials would cause a `401`.

**Comment by jlobos27** [comment]
@KevinTCoughlin yes, i test credentials in postman (app google chrome for requests) and found reblog of post.

**Comment by jlobos27** [comment]
problems in my connection :smile_cat: i test code in koding.com (cloud for developer) and found, thanks!
