### ISSUE TITLE
Support Promise

### ISSUE THREAD

**Issue by noraesae** [tumblr/tumblr.js#51]
For the time being, Promise(or async/await) is considered as a right way to handle asynchronous actions. It would be nice if tumblr.js worked with Promise too.

I have read source code of tumblr.js a little bit and found that Promise can be supported quite easily if we set the `requestLibrary` parameter of the `TumblrClient` constructor as [`request-promise`](https://github.com/request/request-promise). It has compatible APIs with `request`, so I guess it just works without any modification.

Thus, I think there can be several options.

1. Just add the guide above to README
1. Update `tumblr.js` to alternatively use `request-promise` as its request-er. If this option looks better, I'm willing to provide a PR.

Please let me know if there is any comment.

**Comment by kmck** [comment]
Great suggestion! I haven't tried `request-promise` specifically, but if you've done this and determined that it works just as well and that you can chain the Promises, I'm happy to add an example to the README.

For now, I'm going to [integrate native Promises directly](https://github.com/tumblr/tumblr.js/issues/52).

**Comment by noraesae** [comment]
I've tried using `tumblr.js` with `request-promise` in my project and it works well.

```js
import rp from 'request-promise';
import {Client} from 'tumblr.js';

const client = new Client({ /* ... */ }, null, rp);
```

But I didn't know that `request-promise` uses Bluebird. If I had known it did, I would have suggested the native way too. Just to mention, even in `request-promise` it's being considered to use [`any-promise`](https://github.com/kevinbeaty/any-promise) instead of Bluebird .

All in all, I'm happy to see that Promises will be supported natively. I can't wait to use them in the next version. Thanks 👍

**Comment by kmck** [comment]
Closed via https://github.com/tumblr/tumblr.js/pull/52

Thanks for filing the issue!
