### ISSUE TITLE
Missing client.posts() function

### ISSUE THREAD

**Issue by dylancodes** [tumblr/tumblr.js#60]
I'm using the tumblr API console (https://api.tumblr.com/console/calls/blog/posts) to set up my request. I desire to use `client.posts()` to receive an image url, however, `client.posts()` returns a missing function error when I run the command on my machine. 

`client.blogPosts()` works, however, this function does not return the same JSON response that I need to access image urls like `client.posts()` does in the api console.

**Comment by rootion** [comment]
are you using node.js or plain js?

**Comment by jasonpenny** [comment]
@dylancodes you're right, `tumblr.js` changed the function name at some point.
https://api.tumblr.com/console/calls/blog/posts has been updated to show the correct function `client.blogPosts()`, but I don't differences in the JSON response.

Can you add more details here?

**Comment by jasonpenny** [comment]
I think this is solved, now
