### ISSUE TITLE
blogLikes method can get only 11 post

### ISSUE THREAD

**Issue by kotexdammau** [tumblr/tumblr.js#65]
Hi, as title i can't get all blog's likes posts, it just return 11 items only event set "offset=12"

**Comment by kotexdammau** [comment]
userLikes method same error...

**Comment by JEstes93** [comment]
Hello kotexdammau, I'm not having this issue myself. I don't believe this to be a problem with tumblr.js, as my application returns the default 20 results when using both of these methods. I wouldn't mind to review your code for possible mistakes if you would like me to. :)

**Comment by ceyko** [comment]
@kotexdammau I was also unable to replicate testing with no `offset` provided, `offset=10` and `offset=30`. Let me know if you are still seeing this issue.
