### ISSUE TITLE
Question about `taggedPosts`

### ISSUE THREAD

**Issue by mesqueeb** [tumblr/tumblr.js#71]
The docs say to get tagged photos:
`client.taggedPosts(tag, options, callback);`
My questions:
1. What are the option parameters we are able to feed into `options`? That wasn't entirely clear from the docs.
2. I need to see what info the photos in callback will contain. In my case I need to search for multiple tags so get all photos with 1 tag, then in the callback can I see all the tags a photo has per photo?
Is there any example of a callback somewhere?

**Comment by jasonpenny** [comment]
1. The options are documented at https://www.tumblr.com/docs/en/api/v2#tagged-method

2. The response of the callback is a list of posts.
The example below will perform a search for the tag `#dog` limited to 10 posts and output the blog name, post id and all tags for each post that is a photo post:

```javascript
var tumblr = require('tumblr.js');
var client = tumblr.createClient({ consumer_key: '<enter your key here>' });

client.taggedPosts('dog', {limit: 10}, function(err, data) {
    for (var i = 0; i < data.length; ++i) {
        var post = data[i];

        if (post.type === 'photo') {
            console.log(post.blog.name, post.id, post.tags.join(', '));
        }
    }
});
```

**Comment by mesqueeb** [comment]
@jasonpenny Wow! Great support! Thanks! If you don't hear back from me it means everything worked perfectly!
Have a great day!
