### ISSUE TITLE
Error while posting multiple video post at once

### ISSUE THREAD

**Issue by sachinjangid** [tumblr/tumblr.js#73]
Hii all, 

I am working on a project where I am trying to make request to the tumbrl API with the `tumblr.js` module.

When I make a single post request to the API, post is successfully created. But when I send multiple request at a time, it returns error `API error: 403 Forbidden`.  

This is happening for the video posts only for all the other type of posts there is no issue like that.

**Comment by ceyko** [comment]
@sachinjangid This is a limitation of the Tumblr API. You may only have one post transcoding at a time. Once your first post finishes transcoding, you should be able to post a second one, subject to the other limitations mentioned in our [help docs](https://tumblr.zendesk.com/hc/en-us/articles/231455628-Video-posts).

You should be able to see this in the full API response as well:

```
client.createVideoPost(
    blogName,
    {data: myStream},
    function (err,data,resp) { console.log(resp.body); }
);

{"meta":{"status":403,"msg":"Forbidden"},"response":[],"errors":[{"title":"Forbidden","code":8004,"detail":"You have hit a posting or media upload limit for the day."}]}
```

It would be better if `resp.body` were an object instead, as it already is for GET requests, but that's a separate issue we may later address.

**Comment by sachinjangid** [comment]
@ceyko thanks for your reply,

For the successfully shared video post I get message:
 
  ```
  { meta: { status: 201, msg: 'Created' },
      response: 
       { id: 175101177858,
         state: 'transcoding',
         display_text: 'Your video is still processing, please wait a few minutes for it to appear.' } }
```

Here i am not getting the idea that when the "transcoding" will be done, so that I can start requesting the API again for the next video post. 

It would be great if there is any API already exist that tells me the expected transcoding time taken by the current video post. 

Also the docs you suggested, there is limitation for the video post 
    `up to 100MB and 5 minutes per day.`
will you please clear that it should be total video length or it is the time taken for transcoding/processing the video. 

Also the issue you were addressing earlier that the response should be object 

> It would be better if resp.body were an object instead, as it already is for GET requests, but that's a separate issue we may later address.

As you are using request module for tumblr.js you can get response as a object if you simply pass the parameter `json: true`. 
```
const options = {
    url: 'url',
    headers: {...headers}, 
    body: {...body}, 
    json: true // additional parameter need to add if you want response in json,
   form
}

request.post(options)
```
