### ISSUE TITLE
Response body is object for GET and string for POST

### ISSUE THREAD

**Issue by ceyko** [tumblr/tumblr.js#75]
For any GET request, if you inspect `response.body` it is an object. But if you make a POST request, the `response.body` is always a string instead.

``` node
client.createTextPost(
    'longblognamethatdoesntexist',
    { body:'hello there' },
    function(err, data, resp) { typeof console.log(resp.body) }
);
> string

client.blogPosts(
    'longblognamethatdoesntexist',
    {},
    function(err, data, resp) { typeof console.log(resp.body) }
);
> object
```

Ideally it should always be an object, but it is possible that there may be some edge cases (400 or 500 error responses) where the response is not actually JSON as well.

**Comment by shahkashani** [comment]
I think we largely leave the response alone, aside from just converting it to JSON (one level). So, you get something like:

```json
{ 
  "response": { 
    "body": "{}" 
  } 
}
```

Basically, we leave `body` alone in this case, because we don't want to make too many assumptions about the response object.

However, you can do this instead:

```javascript
client.createTextPost(
  'blogname',
  { body:'hello there' },
  function(err, response, body) { console.log(typeof body) }
);

> object
```
