### ISSUE TITLE
Neue Post Format

### ISSUE THREAD

**Issue by oliverjessner** [tumblr/tumblr.js#88]
Will this module be updated to fulfill the [NPF](https://www.tumblr.com/docs/npf) requirements?

**Comment by oliverjessner** [comment]
friendly bump 🙃

**Comment by shahkashani** [comment]
Oh snap, yes. Just made a ticket for this in our internal Jira. Stay tuned!

**Comment by oliverjessner** [comment]
Thanks 😀 I close the issue

**Comment by oliverjessner** [comment]
Hey,

is there a release date for the tumblr.js with support NPF?
Also what happens if an user is still posting HTML, will the lib convert HTML 
to NPF?

warm regards,
Oliver
