### ISSUE TITLE
Replace node's query-string with URLSearchParams

### ISSUE THREAD

**Issue by jimmywarting** [tumblr/tumblr.js#89]
Why?
The WHATWG Standard uses a more selective and fine grained approach to selecting encoded characters than that used by the Legacy API. It's avalible in node, deno and browser, so it will be more light weight when compiling tumblr to eg browser

```diff
- const qs = require('query-string');

...

    return requestGet(extend({
-        url: baseUrl + apiPath + '?' + qs.stringify(params),
+        url: baseUrl + apiPath + '?' + new URLSearchParams(params),
        oauth: credentials,
        json: true,
    }, requestOptions), requestCallback(callback));   
```

```diff
  "dependencies": {
    "lodash": "^4.17.11",
-    "query-string": "^6.1.0",
    "request": "^2.88.0"
  },
```

**Comment by sirreal** [comment]
Thanks, we'll consider this along with the `request` removal.

**Comment by jimmywarting** [comment]
maybe also take the opportunity to replace some lodash things and replace them with native built in solutions. 
maybe even also remove the callback option and depend solo on promises

**Comment by sirreal** [comment]
Yep, work on the 4.0 release required a lot of changes to the library and it made sense to revisit a lot of this. `lodash` and `query-string` were both pretty easy to remove with some of the changes in #153.

> maybe even also remove the callback option and depend solo on promises

The promise API makes sense going forward, but I'm not planning to drop callback support completely in the next release. I do plan to deprecate callbacks.

4.0 is going to have breaking changes, but I'd like to give folks an easier upgrade path so they can get on a modern version quickly and know what the preferred APIs will be in future releases.
