### ISSUE TITLE
Does this work for the browser?

### ISSUE THREAD

**Issue by cyrusdavid** [tumblr/tumblr.js#9]

**Comment by performatric** [comment]
@seejohnrun do you have a example how to works in browser?

I'm trying to work with browserify but now I get CORS errors.

_sorry my english (=_

**Comment by seejohnrun** [comment]
Sorry it's been a few years and I don't have a great example now
What type of call are you trying to make that you're getting CORS errors?

**Comment by ceyko** [comment]
@performatric Unfortunately, the Tumblr API does not currently support CORS requests. It does, however, support JSONP requests which you can use to work around CORS. You might want to look into [this PR](https://github.com/tumblr/tumblr.js/pull/19) (not merged) for inspiration in how you might make it work with the v1.0+ version of tumblr.js.
