### ISSUE TITLE
new post ids are bigger than Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by bobo23** [tumblr/tumblr.js#92]
Hey,
we just recognized that tumblr changed the post ids and there is now an issue.

We posted a text and got the response: 

{
  id: 612752177172201500,
  state: 'published',
  display_text: 'Posted to account'
}

But when we request 'blogPosts' we get for the same post the id: 

612752177172201472

So as you see it's not the same id.

We are assuming that this issue exists because the ids are bigger than the max int.
612752177172201472 < Number.MAX_SAFE_INTEGER === false;

Can you provide the id as a string? That would solve the issue.

Thanx for the help.
Boris

**Comment by cyle** [comment]
Hi there! Yup, we did just increase the size of post IDs. We posted about it here on the Engineering blog: https://engineering.tumblr.com/post/612771063988879360/new-bigger-post-ids

We meant to include the new `id_string` field in these responses but we missed em, but that field should now be present for you! You should be able to use that field interchangeably with `id` when leveraging this library.

**Comment by bobo23** [comment]
Thank you for the response!
