### ISSUE TITLE
Fails to get blog posts if blog unique identifiers is used.

### ISSUE THREAD

**Issue by vipulrawat** [tumblr/tumblr.js#93]
Returns 404 Error, as blog identifier is converted to full url before making the GET request.
So, if I pass `t:DvRFDGL05g8KB0gwiBJv1A` as blog identifier the final request will look like this:
`https://api.tumblr.com/v2/blog/t:DvRFDGL05g8KB0gwiBJv1A.tumblr.com/posts`.

**Comment by sirreal** [comment]
[That form of blog identifier is mentioned in the docs here](https://github.com/tumblr/docs/blob/master/api.md#blog-identifiers) and the [path parameters here](https://github.com/tumblr/docs/blob/master/api.md#request-path-parameters-10), so this should definitely be supported.

**Comment by sirreal** [comment]
According to the API docs, it doesn't look like we need any special handling for blog names. It should understand e.g. `staff`, `staff.tumblr.com` and the blog's unique ID are all the same thing. I've removed that special handling completely in and expect to land that in the next release.
