### ISSUE TITLE
Future of the API

### ISSUE THREAD

**Issue by oliverjessner** [tumblr/tumblr.js#96]
Hey everyone, 

it's been year since the last commit.
Do we know anything about the future of the API/SDK?
Is automattic contributing workforce/money forwards the tumblr API?
Can we expect  any improvements or even new endpoints in the near future?
Is the `NPF` done?

My whole dev team and me are looking forward to your answer.
Warm regards,
Oliver

**Comment by sirreal** [comment]
Do we know anything about the future of the API/SDK?

We'll spend some time getting this library to a better place.

Is automattic contributing workforce/money forwards the tumblr API?

Yep!

Can we expect any improvements or even new endpoints in the near future?

Do you mean exposing more existing endpoints through this library, or something else? If there's something specific you're looking for, let us know!

Is the `NPF` done?

This question is probably a bit out of date, but Tumblr is using NPF and has been for a while.

**Comment by sirreal** [comment]
I'm going to close this issue with a few notes, but please do continue to engage.

I'll leave a bit more information:

- [The NPF spec can be found here](https://www.tumblr.com/docs/npf).
- I plan to include an NPF post creation method in the 4.0 release (#165).

Please continue to issues to let us know what features you're looking for or if you find bugs or other issues. It really helps us to know what direction to take!
