### ISSUE TITLE
tumblr.apiFetch reorder queue

### ISSUE THREAD

**Issue by frapbod** [tumblr/tumblr.js#97]
Hi, I can't find any documentation on the tumblr.apiFetch object you provide on the site. Pretty new to using javascript for anything so bear with me if this is something trivial.

I'm trying to rearrange a queue and from inspecting the network call it seems it takes post_id and insert_after.

Since tumblr was bought by the owners of Wordpress I figured that their Gutenberg project implementation of [api-fetch](https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch) might be similar in usage to the tumblr.apiFetch object they offer.

This is my newest attempt, having to use the path as a positional arg as using it in the object as the example for api-fetch suggests just causes a 404. 
```
tumblr.apiFetch(`/v2/blog/${blog}/posts/queue/reorder`,
    {method: 'POST',
    data: {
        post_id: `${post_id}`,
        insert_after: '0'
    },
                }).then( res => {
    console.log( res );
});
```
But the response still sends back a 400 status. 

Any specific recommendations you'd suggest or is there a better way to do it?

**Comment by sirreal** [comment]
Hi! The `apiFetch` provided for extensions on www.tumblr.com isn't related to the Gutenberg `api-fetch` package.

The example you shared looks pretty close, but you'll need to use `body` instead of `data`. It should look something like this:

```js
tumblr.apiFetch(`/v2/blog/${blog}/posts/queue/reorder`, {
  method: 'POST',
  body: {
    post_id: `${post_id}`,
    insert_after: '0'
  },
}).then(
  res => { console.log( res ) },
  err => { console.error( error ) }
);
```
